# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeBaseUIPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeBaseUIPractice
  pod 'GoogleSignIn'
  target 'CodeBaseUIPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodeBaseUIPracticeUITests' do
    # Pods for testing
  end

end
